# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: bioviz
channels:
  - conda-forge
dependencies:
  - biorbd >=1.12.0
  - matplotlib
  - pyomeca
  - vtk
  - pyqt
