name: Run the tests

on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            label: linux-64
            prefix: /usr/share/miniconda3/envs/bioptim
          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/bioptim
          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\bioptim
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: bioviz
          environment-file: environment.yml
        
      - name: Print conda info
        run: | 
          conda info
          conda list
          
      - name: Install extra dependencies
        run: conda install pytest pytest-cov codecov -cconda-forge 
      
      - name: Install bioviz 
        run: python setup.py install
        
      - name: Run the actual tests on LINUX
        run: | 
          sudo apt-get install xvfb
          xvfb-run --server-args="-screen 0 1024x768x24" pytest -v --color=yes --cov-report term-missing --cov=bioviz tests
        if: matrix.label == 'linux-64' 
          
      - name: Test installed version of bioviz on LINUX
        run: | 
          python setup.py install
          cd
          xvfb-run --server-args="-screen 0 1024x768x24" python -c "import bioviz"
        if: matrix.label == 'linux-64' 
        
      - name: Upload coverage to Codecov
        run: codecov
        if: matrix.label == 'linux-64' 
        
      - name: Run the actual tests on MAC
        run: pytest -v --color=yes --cov-report term-missing --cov=bioviz tests
        if: matrix.label == 'osx-64' 
          
      - name: Test installed version of bioviz on WINDOWS and MAC
        run: | 
          python setup.py install
          cd
          python -c "import bioviz"
        if: matrix.label != 'linux-64' 
        
